config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/event/', to: 'activities#event'
  resources :users
  resources :activities do
    resources :wastes
    resources :likes, only: [:create]
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :activities, dependent: :destroy


  has_one_attached :avatar_photo

  def waste_quantities
    quantities = {}
    user_wastes = self.activities.map { |activity|
      activity.wastes
    }.flatten
    user_wastes.each do |waste|
      quantities[waste.material] = quantities[waste.material] ? quantities[waste.material] + waste.quantity : waste.quantity
    end
    return quantities
  end

    def self.waste_quantities_all
    quantities = {}
    Waste.all.each do |waste|
      quantities[waste.material] = quantities[waste.material] ? quantities[waste.material] + waste.quantity : waste.quantity
    end
    return quantities
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # /users
  def index
    @user = current_user
    @users = User.all
  end

  # users/:id
  def show
    # @user = current_user
    @user = User.find(params[:id])
    @user_wastes = @user.waste_quantities
    @wastes = Waste.all

    @allglass = @user.waste_quantities["Verre"] || 0#? @user.waste_quantities["Verre"] : 0
    @allmetals = @user.waste_quantities["Métal"] || 0#? @user.waste_quantities["Métal"] : 0
    @allPlastics = @user.waste_quantities["Plastique"] || 0#? @user.waste_quantities["Plastique"] : 0
    @allpapers = @user.waste_quantities["Papier"] || 0#? @user.waste_quantities["Papier"] : 0
    @alldivers = @user.waste_quantities["Divers"] || 0#? @user.waste_quantities["Divers"] : 0

    @totalwasteall = @allglass + @allmetals + @allPlastics + @allpapers + @alldivers

    @allglassforchart = @allglass.to_f / @totalwasteall
    @allmetalsforchart = @allmetals.to_f / @totalwasteall
    @allplasticsforchart = @allPlastics.to_f / @totalwasteall
    @allpapersforchart = @allpapers.to_f / @totalwasteall
    @alldiversforchart = @allPlastics.to_f / @totalwasteall

    @totalforchart = @allglassforchart + @allmetalsforchart + @allplasticsforchart + @allpapersforchart + @alldiversforchart
  end

  # -----------   en attente de savoir si utile ----------
  # users/new
  # def new
  #   @user = User.new
  # end

  # # /users
  # def create
  #   @user = User.new(user_params)
  #   if @user.save
  #     redirect_to @user, notice: 'user was successfully created.'
  #   else
  #     render :new
  #   end
  # end
  # ------------------------------------------------------------

  # /users/:id/edit
  def edit
    @user = current_user
    # @user = User.find(params[:id])
  end

  # /users/:id
  def update
    @user = current_user
    # @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'user was successfully updated.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :name, :self_description, :avatar_photo)
  end
end

app/views/users/edit.html.erb
<div class="form-user">
    <%= simple_form_for(@user) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        User's<%= f.input :name %>
        <%= f.input :nickname %>
        <%= f.input :self_description %>
        <%= f.input :avatar_photo, as: :file %>
      </div>

      <div class="form-action">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>

app/views/users/index.html.erb
index

<% @users.each do |user|%>
<li>nickname: <%= link_to user.nickname, user_path(user.id) %>
</li>
  <% if user == current_user %>
  <%= link_to "update profil", edit_user_path(user.id) %>
  <% end %>
<hr>
<%end %>

<%= link_to "home", root_path %>


<%# id => faire lien en savoir + pour self-description jvs %>

app/views/users/new.html.erb
<div class="form-user">
    <%= simple_form_for(@user) do |f| %>
      <%= f.error_notification %>
      <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

      <div class="form-inputs">
        User's<%= f.input :name %>
        <%= f.input :nickname %>
        <%= f.input :self_description %>

      </div>

      <div class="form-action">
        <%= f.button :submit %>
      </div>
    <% end %>
  </div>

app/views/users/show.html.erb
<div class="carte-profil">
  <div class="carte-profil-identite">
    <%= cl_image_tag @user.avatar_photo.key, class: "avatar-carte-profil", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
    <p>
     <% if current_user == @user%>
      <%=@user.name %>
    <% else %>
      <%=@user.name %>
    <% end %>
    </p>
  </div>
  <div class="carte-description-totale">
    <div class="carte-profil-ville">
      <p> <i class="fas fa-street-view"></i> <%= @user.city %></p>
    </div>
    <div class="carte-profil-description">
      <p> <%= @user.self_description %></p>
    </div>
  </div>
</div>

<div class="card-trip">
  <div class="dash-content">
    <h3 style="text-align: center; font-size: 26px;">Communauté MoonFlowers </h3>
    <div class="donut" style="--first: <%= @allplasticsforchart %>; --second: <%= @allmetalsforchart %>; --third: <%= @allpapersforchart %>; --fourth: <%= @allglassforchart %>; --fifth: <%= @alldiversforchart %>">
      <div class="donut__slice donut__slice__first"></div>
      <div class="donut__slice donut__slice__second"></div>
      <div class="donut__slice donut__slice__third"></div>
      <div class="donut__slice donut__slice__fourth"></div>
      <div class="donut__slice donut__slice__fifth"></div>
      <div class="donut__label">
        <div class="donut__label__heading">
          <% if current_user == @user%>
            Mes résultats
          <% else %>
            Ses résultats
          <% end %>
        </div>
        <div class="donut__label__sub">
          en chiffres
        </div>
      </div>
    </div>


    <div class="mega-div-dechet">
      <div class="dechet-colonnes">
        <div class="dechet-col-1">
          <span style="font-size: 1em; color: #ff6838; ">
            <i class="fas fa-dot-circle"></i> Plastique<%=@allPlastics>1 ? "s" : ""%> <%= @allPlastics %>
          </span>
          <span style="font-size: 1em; color: #ffc820; ">
            <i class="fas fa-dot-circle"></i> Méta<%=@allmetals>1 ? "ux" : "l"%> <%= @allmetals %>
          </span>

          <span style="font-size: 1em; color: #97c95c; ">
            <i class="fas fa-dot-circle"></i> Papier<%=@allpapers>1 ? "s" : ""%> <%= @allpapers %>
          </span>
        </div>

        <div class="dechet-col-2">
          <span style="font-size: 1em; color: #1cb2f6; ">
            <i class="fas fa-dot-circle"></i> Verre<%=@allglass>1 ? "s" : ""%> <%= @allglass %>
          </span>
          <span style="font-size: 1em; color: #1685b8; ">
            <i class="fas fa-dot-circle"></i> Divers <%= @alldivers %>
          </span>
        </div>
        <br>

      </div>

      <span style="font-size: 1em; color: #cf6626; display: flex; justify-content: center; margin-top: 10px;">
        Total = <%= @totalwasteall %> déchet<%=@totalwasteall>1 ? "s" : ""%>
      </span>
    </div>


  </div>
</div>



  <div class="card-trip-scroll">
    <div class="dash-content">

<div class="actions-content">
  <% if current_user == @user%>
    <h2>Mes actions</h2>
  <% else %>
    <h2>Ses actions </h2>
  <% end %>
</div>
      <% @user.activities.order(created_at: :desc).each do |activity| %>
          <div class="actions-content">

            <div class="carte-activite-description">
              <% if activity.waste %>
                <%= activity.created_at.to_time.strftime('%d/%m/%Y à %l:%M %p') %>

                <p>Total collecté:
                  <% @totaluser = 0 %>
                  <% activity.wastes.each do |waste| %>
                  <% @totaluser += waste.quantity %>
                  <% end %>
                  <%= @totaluser %>
                </p>

                <p><%= activity.address %></p>
              <% end %>
            </div>
            <div class="carte-activite-boutons">
              <% if activity.user == current_user %>
                <%= link_to activity_path(activity), method: :delete, data: { confirm: 'Etes vous sûr de vouloir supprimer cette action?' } do %>
                <i class="far fa-trash-alt fa-sm" style="color: black;"></i>
                <% end %>
              <% end %>

              <div class="lien-detail"><%= link_to "Voir détails", activity_path(activity) %></div>
              <div class="like">
                <div class="heart">
                  <i class="fas fa-heart" ></i>
                </div>
                <div class="like-count">
                  <%= activity.likes.count  %>
                </div>
              </div>
            </div>
          </div>
      <% end %>
    </div>
  </div>