config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/event/', to: 'activities#event'
  resources :users
  resources :activities do
    resources :wastes
    resources :likes, only: [:create]
  end

end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="mainFooterAnchor">
 <div class="pied-de-page">
    <div class="footer-links">

     <a href="#"><i class="fab fa-instagram"></i></a>
     <a href="#"><i class="fab fa-facebook"></i></a>
     <a href="#"><i class="fab fa-twitter"></i></a>
     <a href="#"><i class="fab fa-youtube"></i></a>

   </div>
   <div><p>Copyright ©2021 </p></div>
  </div>
</div>

app/views/shared/_info_window.html.erb
<div class="btnmap">
<%= link_to activity_path(activity.id) do %>
  <h2 class="map-user-name"><%= activity.user.nickname %></h2>
<% end %>
<p class="map-address-activity"><%= activity.address%></p>
</div>

<div style="color: red;"><i class="fas fa-heart" ></i> <%= activity.likes.count%></div>

app/views/shared/_info_window_new_act.html.erb
<p class="map-address-activity">Vous êtes ici</p>

app/views/shared/_navbar.html.erb
<div id="mainMenuBarAnchor">
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" id="menu">
  <%= link_to root_path, class: "navbar-brand" do %>
  <h3>MoonFlowers</h3>
    <%= image_tag "https://image.flaticon.com/icons/png/512/3024/3024889.png" %>
    <p class="navbar-accueil"> Accueil </p>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item dropdown">
          <%= image_tag "https://image.flaticon.com/icons/png/512/861/861143.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <p>Nos Actions</p>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "S'aime ton Action", new_activity_path, class: "dropdown-item" %>
            <%= link_to "Crée ton Événement", "", class: "dropdown-item" %>
            <%= link_to "Contacter la Mairie ", "#", class: "dropdown-item" %>
          </div>
        </li>

        <li class="nav-item dropdown">
          <%= image_tag "https://image.flaticon.com/icons/png/512/4474/4474452.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <p>Notre Communauté</p>
          <div class="dropdown-menu dropdown-menu-right nav-middle" aria-labelledby="navbarDropdown">
            <%= link_to "Communauté", activities_path, class: "dropdown-item" %>
            <%= link_to "Forum", "#", class: "dropdown-item" %>
            <%= link_to "Evènements", event_path, class: "dropdown-item" %>
          </div>
        </li>

        <li class="nav-item dropdown">

        <%= cl_image_tag current_user.avatar_photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>

          <p>Mon Profil</p>
          <div class="dropdown-menu dropdown-menu-right nav-right" aria-labelledby="navbarDropdown">
            <%= link_to "Mon Profil", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %>
        <div class="alignright">
        <li class="nav-item">
          <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
        </li>
        </div>
      <% end %>
    </ul>
  </div>
</div>
</div>