config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/event/', to: 'activities#event'
  resources :users
  resources :activities do
    resources :wastes
    resources :likes, only: [:create]
  end

end

app/models/activity.rb
class Activity < ApplicationRecord
  belongs_to :user
  has_many :wastes, dependent: :destroy
  has_many :likes, dependent: :destroy

  accepts_nested_attributes_for :wastes

  reverse_geocoded_by :latitude, :longitude do |activity, results|
    if geo = results.first
      activity.address = geo.street + ", "+ geo.city
    end
  end
  after_validation :reverse_geocode



  def waste
    wastes.first
  end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  # get /activities -actions_path
  def index
    @activities = Activity.all
    # the `geocoded` scope filters only flats with coordinates (latitude & longitude)
    @markers = @activities.geocoded.map do |activity|
      {
        lat: activity.latitude,
        lng: activity.longitude,
        info_window: render_to_string(partial: "shared/info_window", locals: { activity: activity }),
        image_url: helpers.asset_url('moon-green.png')
      }
    end

    @users = User.all
    @wastes = Waste.all

    @allglass = User.waste_quantities_all["Verre"] || 0 #? User.waste_quantities_all["Verre"] : 0
    @allmetals = User.waste_quantities_all["Métal"] || 0#? User.waste_quantities_all["Verre"] : 0
    @allPlastics = User.waste_quantities_all["Plastique"] || 0#? User.waste_quantities_all["Verre"] : 0
    @allpapers = User.waste_quantities_all["Papier"] || 0#? User.waste_quantities_all["Verre"] : 0
    @alldivers = User.waste_quantities_all["Divers"] || 0#? User.waste_quantities_all["Verre"] : 0

    @totalwasteall = @allglass + @allmetals + @allPlastics + @allpapers + @alldivers

    @allglassforchart = @allglass.to_f / @totalwasteall.to_f
    @allmetalsforchart = @allmetals.to_f / @totalwasteall.to_f
    @allplasticsforchart = @allPlastics.to_f / @totalwasteall.to_f
    @allpapersforchart = @allpapers.to_f / @totalwasteall.to_f
    @alldiversforchart = @allPlastics.to_f / @totalwasteall.to_f

    @totalforchart = @allglassforchart + @allmetalsforchart + @allplasticsforchart + @allpapersforchart + @alldiversforchart

  end

  # get /activities/:id -action_path
  def show
    @activity = Activity.find(params[:id])

    @total = 0
    @activity.wastes.each do |waste|
      @total += waste.quantity
    end

    @markers = [{
      lat: @activity.latitude,
      lng: @activity.longitude,
      info_window: render_to_string(partial: "shared/info_window", locals: { activity: @activity }),
      image_url: helpers.asset_url('moon-green.png')

    }]

  end

  # get /activities/new -new_action_path
  def new
    @activity = Activity.new
    @activity.wastes.build

    @markers = [{
      lat: @activity.latitude,
      lng: @activity.longitude,
      info_window: render_to_string(partial: "shared/info_window_new_act", locals: { activity: @activity }),
      image_url: helpers.asset_url('moon-red.png')

    }]
  end

  # post /activities -action_path
  def create
    @activity = Activity.new(activities_params)
    @activity.user = current_user

    if @activity.save
      unless params[:verre] == ""
        @waste = Waste.new
        @waste.material = "Verre"
        @waste.quantity = params[:verre].to_i
        @waste.activity = @activity
        @waste.save
      end
      unless params[:papier] == ""
        @waste = Waste.new
        @waste.material = "Papier"
        @waste.quantity = params[:papier].to_i
        @waste.activity = @activity
        @waste.save
      end
      unless params[:plastique] == ""
        @waste = Waste.new
        @waste.material = "Plastique"
        @waste.quantity = params[:plastique].to_i
        @waste.activity = @activity
        @waste.save
      end
      unless params[:metal] == ""
        @waste = Waste.new
        @waste.material = "Métal"
        @waste.quantity = params[:metal].to_i
        @waste.activity = @activity
        @waste.save
      end
      unless params[:divers] == ""
        @waste = Waste.new
        @waste.material = "Divers"
        @waste.quantity = params[:divers].to_i
        @waste.activity = @activity
        @waste.save
      end
      redirect_to @activity, notice: 'Votre action a été correctement ajoutée.'

      @markers = [{
        lat: @activity.latitude,
        lng: @activity.longitude,
        info_window: render_to_string(partial: "shared/info_window_new_act", locals: { activity: @activity }),
        image_url: helpers.asset_url('moon.png')
      }]

    else
      render :new
    end
  end

  # get /activities/:id/edit -edit_action_path
  def edit
    @activity = Activity.find(params[:id])
  end

  # patch(post?) /activities/:id -action_path
  def update
    @activity = Activity.find(params[:id])
    if @activity.update(activities_params)
      redirect_to @activity, notice: 'Votre action a été correctement mise à jour.'
    else
      render :edit
    end
  end

  # delete /activities/:id -action_path
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to user_path(current_user), notice: 'Votre action a été supprimée.'
  end

  private

  def activities_params
    params.require(:activity).permit(:longitude, :latitude, wastes_attributes: [:material, :quantity])
  end

  def wastes_params
    params[:activity].require(:waste).permit(:material, :quantity)
  end

end

app/views/activities/edit.html.erb
<div class="card-trip">

    <div class="form-div">
      <h2>Modification de la collecte</h2>

      <div class=“form-action-new”>

        <%= simple_form_for (@activity) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
          <%= f.input :latitude %>
          <%= f.input :longitude %>

            <%= f.simple_fields_for Waste.new do |waste| %>
              <div class="form-waste">
                <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material01" aria-expanded="false" aria-controls="material01"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/1039/1039781.png" alt="boîte en carton Icône gratuit" title="boîte en carton Icône gratuit" class="loaded">
                </button>
                <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material02" aria-expanded="false" aria-controls="material02"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/1039/1039780.png" alt="boîte en carton Icône gratuit" title="boîte en carton Icône gratuit" class="loaded">
                </button>
                <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material03" aria-expanded="false" aria-controls="material03"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/1039/1039778.png" alt="Plastic bottle free icon" title="Plastic bottle free icon" class="loaded">
                </button>
                <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material04" aria-expanded="false" aria-controls="material04"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/1039/1039782.png" alt="Plastic bottle free icon" title="Plastic bottle free icon" class="loaded">
                </button>
                <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material05" aria-expanded="false" aria-controls="material04"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/1039/1039763.png" alt="Plastic bottle free icon" title="Plastic bottle free icon" class="loaded">
                </button>
              </div>
            <% end %>

              <div class="d-flex justify-content-center">
                <div class="col-waste">
                  <div class="collapse multi-collapse" id="material01">
                    <div class="card card-body card-waste">
                      <input name="verre" type="number" class="input-waste" placeholder="0">
                    </div>
                  </div>
                </div>
                <div class="col-waste">
                  <div class="collapse multi-collapse" id="material02">
                    <div class="card card-body card-waste">
                      <input name="papier" type="number" class="input-waste" placeholder="0">
                    </div>
                  </div>
                </div>
                <div class="col-waste">
                  <div class="collapse multi-collapse" id="material03">
                    <div class="card card-body card-waste">
                      <input name="plastique" type="number" class="input-waste" placeholder="0">
                    </div>
                  </div>
                </div>
                <div class="col-waste">
                  <div class="collapse multi-collapse" id="material04">
                    <div class="card card-body card-waste">
                      <input name="metal" type="number" class="input-waste" placeholder="0">
                    </div>
                  </div>
                </div>
                <div class="col-waste">
                  <div class="collapse multi-collapse" id="material05">
                    <div class="card card-body card-waste">
                      <input name="divers" type="number" class="input-waste" placeholder="0">
                    </div>
                  </div>
                </div>
              </div>
      <div class="form-actions">
        <%= f.button :submit %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/event.html.erb
<div class="card-trip">
  <img src="https://madeinmarseille.net/actualites-marseille/2018/04/ramassage-dechet-operation-sensiboat.jpeg" />
  <div class="card-trip-infos">
    <div class="textevent">
      <h2>Nettoyage plage des catalans</h2>
      <p>Samedi 4 septembre 2021 à 14h00</p>
    </div>
    <button type="button" class="btn-event faux" >PARTICIPER</button>
  </div>
</div>


<div class="card-trip">
  <img src="https://previews.123rf.com/images/dolgachov/dolgachov1708/dolgachov170801117/83942590-voluntarios-con-bolsas-de-basura-limpieza-de-%C3%A1rea-del-parque.jpg" />
  <div class="card-trip-infos">
    <div class="textevent">
      <h2>Nettoyage du parc Longchamps</h2>
      <p>Dimanche 19 septembre 2021 à 11h00</p>
    </div>
    <button type="button" class="btn-event faux" >PARTICIPER</button>
  </div>
</div>

<div class="card-trip">
  <img src="https://france3-regions.francetvinfo.fr/image/mSHKH1JPY1v0oZycT8S_X6zSKbA/600x400/regions/2020/06/09/5edf28ecd727d_maxnewsworldfour243456-2964721.jpg" />
  <div class="card-trip-infos">
    <div class="textevent">
      <h2>Nettoyage de nos rue, Marseille</h2>
      <p>Mercedri 13 octobre 2021 à 18h00</p>
    </div>
    <button type="button" class="btn-event faux" >PARTICIPER</button>
  </div>
</div>

<div class="card-trip">
  <img src="https://pbs.twimg.com/media/D9fdBulXkAAf0E3.png" />
  <div class="card-trip-infos">
    <div class="textevent">
      <h2>Nettoyage fonds marin de la Corniche</h2>
      <p>Dimanche 31 octobre 2021 à 9h30</p>
    </div>
    <button type="button" class="btn-event faux" >PARTICIPER</button>
  </div>
</div>

app/views/activities/index.html.erb
<div class="card-trip">
  <div class="dash-content">
    <h3>Communauté MoonFlowers </h3>
    <div class="donut" style="--first: <%= @allplasticsforchart %>; --second: <%= @allmetalsforchart %>; --third: <%= @allpapersforchart %>; --fourth: <%= @allglassforchart %>; --fifth: <%= @alldiversforchart %>">
      <div class="donut__slice donut__slice__first"></div>
      <div class="donut__slice donut__slice__second"></div>
      <div class="donut__slice donut__slice__third"></div>
      <div class="donut__slice donut__slice__fourth"></div>
      <div class="donut__slice donut__slice__fifth"></div>
      <div class="donut__label">
        <div class="donut__label__heading">
          Nos résultats
        </div>
        <div class="donut__label__sub">
          en chiffres
        </div>
      </div>
    </div>

    <div class="mega-div-dechet">
    <div class="dechet-colonnes">
        <div class="dechet-col-1">
          <span style="font-size: 1em; color: #ff6838; ">
            <i class="fas fa-dot-circle"></i> Plastique<%= @allPlastics>1 ? "s" : ""%> <%= @allPlastics%>
          </span>
          <span style="font-size: 1em; color: #ffc820; ">
            <i class="fas fa-dot-circle"></i> Méta<%=@allmetals>1 ? "ux" : "l"%> <%= @allmetals %>
          </span>

          <span style="font-size: 1em; color: #97c95c; ">
            <i class="fas fa-dot-circle"></i> Papier<%=@allpapers>1 ? "s" : ""%> <%= @allpapers %>
          </span>
        </div>

        <div class="dechet-col-2">
          <span style="font-size: 1em; color: #1cb2f6; ">
            <i class="fas fa-dot-circle"></i> Verre<%=@allglass>1 ? "s" : ""%> <%= @allglass %>
          </span>
          <span style="font-size: 1em; color: #1685b8; ">
            <i class="fas fa-dot-circle"></i> Divers <%= @alldivers %>
          </span>
        </div>
        <br>
      </div>

      <span style="font-size: 1em; color: #cf6626; display: flex; justify-content: center; margin-top: 10px;">
        Total = <%= @totalwasteall %> déchet<%=@totalwasteall>1 ? "s" : ""%>
      </span>
    </div>

  </div>
</div>

<div class="card-trip">
  <div class="dash-content">
    <div id="map"
    style="width: 100%; height: 350px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>
  </div>
</div>

app/views/activities/new.html.erb
<div class="card-trip">

  <div class="form-div">
    <h2>Voici ta position</h2>

      <div id="map-new-activity"
        style="width: 100%; height: 280px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
      <div class=“form-action-new”>
        <%= simple_form_for (@activity) do |f| %>
          <%= f.error_notification %>
          <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
        <div class ="hidden input" style="margin-bottom: -94px">
          <%= f.input :latitude %>
          <%= f.input :longitude %>
        </div>

        <h2>Clique et ajoute</h2>

        <%= f.simple_fields_for Waste.new do |waste| %>
          <div class="form-waste">
            <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material01" aria-expanded="false" aria-controls="material01">
              <img width="60" height="60" src="https://image.flaticon.com/icons/png/512/4185/4185152.png" alt="" title="Verres" class="loaded">
              <div class="bottomtext"><a>verre</a></div>
            </button>
            <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material02" aria-expanded="false" aria-controls="material02">
              <img width="60" height="60" src="https://image.flaticon.com/icons/png/512/1598/1598172.png" alt="" title="Papiers" class="loaded">
               <div class="bottomtext"><a>papier</a></div>
           </button>
            <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material03" aria-expanded="false" aria-controls="material03">
              <img width="60" height="60" src="https://image.flaticon.com/icons/png/512/4380/4380438.png" alt="" title="Plastiques" class="loaded">
               <div class="bottomtext"><a>plastique</a></div>
            </button>
            <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material04" aria-expanded="false" aria-controls="material04">
              <img width="60" height="60" src="https://image.flaticon.com/icons/png/512/2372/2372106.png" alt="" title="Métaux" class="loaded">
               <div class="bottomtext"><a>metal</a></div>
            </button>
            <button class="btn btn-primary btn-waste" type="button" data-toggle="collapse" data-target="#material05" aria-expanded="false" aria-controls="material04">
              <img width="60" height="60" src="https://image.flaticon.com/icons/png/512/4815/4815240.png" alt="" title="Divers" class="loaded">
               <div class="bottomtext"><a>divers</a></div>
            </button>
          </div>
        <% end %>

          <div class="inputs-waste">
            <div class="col-waste">
              <div class="collapse multi-collapse" id="material01">
                <div class="card card-body card-waste">
                  <input name="verre" type="number" class="input-waste" placeholder="0">
                </div>
              </div>
            </div>
            <div class="col-waste">
              <div class="collapse multi-collapse" id="material02">
                <div class="card card-body card-waste">
                  <input name="papier" type="number" class="input-waste" placeholder="0">
                </div>
              </div>
            </div>
            <div class="col-waste">
              <div class="collapse multi-collapse" id="material03">
                <div class="card card-body card-waste">
                  <input name="plastique" type="number" class="input-waste" placeholder="0">
                </div>
              </div>
            </div>
            <div class="col-waste">
              <div class="collapse multi-collapse" id="material04">
                <div class="card card-body card-waste">
                  <input name="metal" type="number" class="input-waste" placeholder="0">
                </div>
              </div>
            </div>
            <div class="col-waste">
              <div class="collapse multi-collapse" id="material05">
                <div class="card card-body card-waste">
                  <input name="divers" type="number" class="input-waste" placeholder="0">
                </div>
              </div>
            </div>
          </div>

        <div class="form-actions">
          <input type="submit" name="commit" value="Valide" class="btn" data-disable-with="Valide">
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/activities/show.html.erb
<br>
<div class="container-action-show">
</div>

<div class="card-trip">
  <div class="dash-content">
       <div class="like-head">
       <h3>Collecte de <%= link_to user_path(@activity.user) do%>
       <%=@activity.user.nickname %>
       <% end %>
       </h3>
          <div class="like">
              <div class="heart"><%= link_to activity_likes_path(@activity), method: :create do %><i class="fas fa-heart" style="color: red;"></i><% end %></div>
              <div class="like-count"><%= @activity.likes.count%></div>
          </div>
      </div>



  <div class="wastescard">
    <p>  Adresse : <%= @activity.address %></p>
  <div class="wastes-show">
    <% if @activity.waste %>
        <% @activity.wastes.each do |waste| %>
          <% case waste.material %>
                <% when "Verre" %>
                    <div class="uniq_wastes"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/4185/4185152.png" alt="poubelle verre"><div class="number"><%= waste.quantity %></div></div>
                <% when "Papier" %>
                    <div class="uniq_wastes"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/1598/1598172.png" alt="poubelle papier"><div class="number"><%= waste.quantity %></div></div>
                <% when "Plastique" %>
                    <div class="uniq_wastes"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/4380/4380438.png" alt="poubelle plastique"><div class="number"><%= waste.quantity %></div></div>
                <% when "Métal" %>
                    <div class="uniq_wastes"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/2372/2372106.png" alt="poubelle métal"><div class="number"><%= waste.quantity %></div></div>
                <% else %>
                    <div class="uniq_wastes"><img width="60" height="60" src="https://image.flaticon.com/icons/png/512/4815/4815240.png" alt="poubelle divers"><div class="number"><%= waste.quantity %></div></div>
          <% end %>
        <% end %>
      <% end %>
  </div>
    <div class="total"> Total : <%=@total%> déchet<%=@total>1 ? "s" : ""%></div>

    <% if @activity.user == current_user %>
      <%= link_to activity_path, method: :delete, data: { confirm: 'Etes vous sur de vouloir supprimer cette action?' } do %>
      <i class="far fa-trash-alt fa-sm trash" style="margin-bottom: 7px; color: black;"></i>
      <% end %>
    <% end %>

  </div>
</div>
</div>

<div class="card-trip">
  <div class="btnje">
  Jette un coup d'oeil à la Communauté
<div class="comm">
   <%= link_to activities_path do %>
   <%= image_tag "https://image.flaticon.com/icons/png/512/4474/4474452.png" %>
   <% end %>
</div>
  </div>
</div>

<div class="card-trip">
<div class="dash-content">
  <div class="textmiddle"><h5>Lieu d'action</h5></div>

  <div class="map-action-show">
      <div id="map"
        style="width: 100%; height: 280px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>
  </div>
</div>
</div>